export const FETCH_MESSAGES_REQUEST = 'FETCH_MESSAGES_REQUEST';
export const ADD_MESSAGES = 'ADD_MESSAGES';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const CREATE_CONNECTION = 'CREATE_CONNECTION';
